# Generated by Django 6.0.3 on 2026-04-07 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('ticker', models.CharField(db_column='Ticker', max_length=10, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_column='Company_Name', max_length=50)),
            ],
            options={
                'db_table': 'COMPANY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_favourited', models.DateField(db_column='DateFavourited')),
            ],
            options={
                'db_table': 'FAVOURITE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Updatescompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'UPDATESCOMPANY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Updatesfinmetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'UPDATESFINMETRICS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Updatesproductiondata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_column='Period', max_length=20)),
            ],
            options={
                'db_table': 'UPDATESPRODUCTIONDATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Updatesstockprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateField(db_column='Date_Updated')),
            ],
            options={
                'db_table': 'UPDATESSTOCKPRICE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usertab',
            fields=[
                ('user_id', models.AutoField(db_column='User_ID', primary_key=True, serialize=False)),
                ('user_fname', models.CharField(db_column='User_FName', max_length=50)),
                ('user_lname', models.CharField(db_column='User_LName', max_length=50)),
                ('user_email', models.CharField(db_column='User_Email', max_length=100, unique=True)),
                ('user_password', models.CharField(db_column='User_Password', max_length=200)),
                ('permission_level', models.CharField(choices=[('Investor', 'Investor'), ('Admin', 'Admin')], db_column='Permission_Level', max_length=10)),
                ('is_active', models.BooleanField(db_column='Is_Active', default=False)),
            ],
            options={
                'db_table': 'USERTAB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Viewsdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'VIEWSDETAILS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Finmetrics',
            fields=[
                ('ticker', models.OneToOneField(db_column='Ticker', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='finmetrics', serialize=False, to='mining.company')),
                ('aisc', models.DecimalField(db_column='AISC', decimal_places=2, max_digits=12)),
                ('peg', models.DecimalField(db_column='PEG', decimal_places=2, max_digits=6)),
                ('total_debt', models.DecimalField(db_column='TotalDebt', decimal_places=2, max_digits=15)),
                ('debt_to_equity', models.DecimalField(db_column='DebtToEquity', decimal_places=2, max_digits=6)),
                ('revenue', models.DecimalField(db_column='Revenue', decimal_places=2, max_digits=15)),
                ('ebitda', models.DecimalField(db_column='EBITDA', decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'FINMETRICS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productiondata',
            fields=[
                ('ticker', models.ForeignKey(db_column='Ticker', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='production_records', serialize=False, to='mining.company')),
                ('period', models.CharField(db_column='Period', max_length=20)),
                ('silver_ounces_produced', models.DecimalField(blank=True, db_column='SilverOuncesProduced', decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
            ],
            options={
                'db_table': 'PRODUCTIONDATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rankingreport',
            fields=[
                ('ticker', models.OneToOneField(db_column='Ticker', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mining.company')),
                ('score', models.DecimalField(db_column='Score', decimal_places=2, max_digits=5)),
                ('rank_position', models.IntegerField(db_column='RankPosition')),
            ],
            options={
                'db_table': 'RANKINGREPORT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stockprice',
            fields=[
                ('ticker', models.ForeignKey(db_column='Ticker', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock_prices', serialize=False, to='mining.company')),
                ('date_updated', models.DateField(db_column='Date_Updated')),
                ('previous_open', models.DecimalField(blank=True, db_column='PreviousOpen', decimal_places=2, max_digits=10, null=True)),
                ('previous_close', models.DecimalField(blank=True, db_column='PreviousClose', decimal_places=2, max_digits=10, null=True)),
                ('fifty_two_week_high', models.DecimalField(blank=True, db_column='FiftyTwoWeekHigh', decimal_places=2, max_digits=10, null=True)),
                ('fifty_two_week_low', models.DecimalField(blank=True, db_column='FiftyTwoWeekLow', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'STOCKPRICE',
                'managed': False,
            },
        ),
    ]
